### ISSUE TITLE
Release v2.1.0 final to unlock Scala Center's SCP-026

### ISSUE THREAD

**Issue by sjrd** [coursier/coursier#2334]
Hello,

Coursier v2.1.0-M1 was released 2 months ago, with an M2 a couple weeks later. Since then, there does not appear to have been any changes in the `master` branch, and it also seems that no critical regression was reported.

**May I kindly ask to release Coursier v2.1.0 final?**

As long as there is no final release, we cannot merge the following PRs in coursier/apps:

* https://github.com/coursier/apps/pull/119
* https://github.com/coursier/apps/pull/113

Merging those PRs is required to move forward with [the Scala Center Recommendation SCP-026](https://github.com/scalacenter/advisoryboard/blob/main/proposals/026-solidify-getting-started-with-coursier.md), which has therefore been blocked.

Using the milestone is, in theory, possible. But you need to create your own channel with the changes brought by the two PRs above. This is not something we can recommend to newcomers.

/cc @adpi2 @ckipp01 @tpolecat

**Comment by alexarchambault** [comment]
As discussed via other channels, I don't think we really need a "stable" version for the CLI.

I'd like to change the API a bit more before going back to stable version numbers (I'd like to rely on [coursier/dependency](https://github.com/coursier/dependency) and [coursier/versions](https://github.com/coursier/versions) in particular, and drop the former APIs these replace).

To me, the coursier version reflects only the stability of the API. The CLI itself is stable enough (there's plenty of non regression tests, ensuring it is), and doesn't really break its "public interface", that is its CLI options.

I'm not sure, but it seems to me that part of your wish for a "stable" version may originate from the coursier website not being updated recently (it had been on `2.0.13` for a while, and only changed during the last two days). The CI jobs updating the website had issues since the switch of the coursier build to Mill. These are fixed now, by https://github.com/coursier/coursier/pull/2347 in particular.

I still need to update [coursier/setup-action](https://github.com/coursier/setup-action) (its master is already using the latest launchers, only a stable release of coursier/setup-action should be needed IIRC).

**Comment by julienrf** [comment]
Thank you for your response. Let me clarify what I mean by a “stable” release of the CLI. Basically, we would like to fix a couple of issues with the current behavior of `cs`. Notably, #1957, which is addressed by coursier/apps#119. There are a couple of other PRs open in coursier/apps, such as coursier/apps#113 and coursier/apps#122. I am not sure what are the blockers for these PRs to be merged, maybe they don’t need a new stable release of Coursier. It would be good to clarify how we could get them merged.

**Comment by sjrd** [comment]
> I'm not sure, but it seems to me that part of your wish for a "stable" version may originate from the coursier website not being updated recently (it had been on `2.0.13` for a while, and only changed during the last two days). The CI jobs updating the website had issues since the switch of the coursier build to Mill. These are fixed now, by #2347 in particular.

I just tried again from scratch, following [the installation instructions](https://get-coursier.io/docs/cli-installation), and what is installed is still `cs` 2.0.13. That means that we cannot merge https://github.com/coursier/apps/pull/119 and https://github.com/coursier/apps/pull/113, and that `cs --help` still shows the help menus before all the beginner-friendly improvements.

--> So my wish for a stable version is really that, if I follow the standard instructions on the website, I get a version of `cs` that has all the improvements that are currently in the Milestones. So that we can merge the above two PRs in `coursier/apps`.

If following the standard instructions installs `cs` 2.1.0-Mx`, then I'm fine with it, and we should merge the two PRs. Ideally, for people who have already installed a previous version, `cs update` should also install 2.1.0-Mx then. Otherwise we need to tell everyone to reinstall it, or force-update or something.

**Comment by ckipp01** [comment]
I'm a bit confused by what the plan is here now I see https://github.com/coursier/apps/pull/119 was merged, but I was under the assumption it wouldn't be until a stable release _or_ everything was on the latest milestone.  CI builds that are using coursier/setup-action are now failing with the issue mentioned here: https://github.com/coursier/coursier/issues/2351.

Are we forcing the Milestone on people? Are we doing a stable release?

**Comment by sjrd** [comment]
(on Windows)

OK, so, trying any combination `cs update something`, including with `cs` being the newest installer, did *not* update `cs` to the latest milestone, even I explicitly specified it.

However, after deleting `AppData\Local\Coursier\data\bin` entirely, and doing a new `".\cs-x86_64-pc-win32.exe" setup` from scratch, I received what must be `cs` 2.1.0-something, along with the native `sbt` launcher. This was not the case a couple days ago when I last tried. So something definitely seems to have progressed here.

Thank you!

**Comment by julienrf** [comment]
It turned out that releasing a final v2.1.0 was not necessary to ship the work done by the Scala Center into the hands of the Scala users. This issue can be closed.

**Comment by alexarchambault** [comment]
Closing this, as the root of the issue (benefitting from fixes in the "default" CLI) has been fixed, with apparently non-stable version of the CLI being recommended in most places (being understood that version numbers stability applies less to the CLI, and more to the API stability).

**Comment by ckipp01** [comment]
For what it's worth, I'd still recommend doing a stable release. There are places that use coursier that have strict policies on versions that they can use. For example at the client I work at we aren't allowed to use non-stable versions, meaning we can't use anything newer than 2.0.16 because everything else is seen as a non-stable version. Please reconsider this. I know "it's just a number", but that doesn't work in a ton of enterprise-type companies. If it doesn't matter to you like you say, then just release a new stable version.

**Comment by sideeffffect** [comment]
> 2.0.16

Which happened more than one and half year ago https://github.com/coursier/coursier/releases/tag/v2.0.16
New stable release would surely be warmly welcomed :heart:

**Comment by alexarchambault** [comment]
I might cut `2.1.0` final then (and probably start using `2.2.0` milestone versions soon after).

**Comment by SethTisue** [comment]
2.1.0-RC6 came out yesterday. Do all these PCs mean 2.1.0 is now imminent? Or we have we replaced a potentially endless series of milestones with a potentially endless series of RCs...?

**Comment by SethTisue** [comment]
yayyy!!! https://github.com/coursier/coursier/releases/tag/v2.1.0  👏😍
